### ISSUE TITLE
pull request into the main dropwizard/metrics repository

### ISSUE THREAD

**Issue by gbmeuk** [omnifone/metrics-zabbix#1]
Hey Manish,

Have you thought about tidying this up a little by making it require the [main JAX-RS libraries](https://github.com/resteasy/Resteasy) and not the internal one, then submitting a pull request to the [main dropwizard/metrics repository](https://github.com/dropwizard/metrics)?  There are official reporter modules for [Graphite](http://metrics.dropwizard.io/3.1.0/manual/graphite/#manual-graphite) and [Ganglia](http://metrics.dropwizard.io/3.1.0/manual/ganglia/#manual-ganglia)

G

**Comment by mkumaromnifone** [comment]
updated as requested

**Comment by mkumargithub** [comment]
updated as requested
